[package]
name = "wookie"
version = "0.1.1"
description = "A very small and fast executor for one Future on one thread. Lightweight enough to have many of them."
keywords = ["async", "futures", "executor", "no-std"]
categories = ["asynchronous", "concurrency", "no-std"]
authors = ["James Laver <james.laver@gmail.com>"]
homepage = "https://github.com/irrustible/wookie"
repository = "https://github.com/irrustible/wookie"
documentation = "https://docs.rs/wookie"
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"

[dev-dependencies]
futures-micro = "0.5"

[dependencies]
pin-project-lite = "0.2"
